# Generated by Django 4.1.3 on 2023-02-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0004_user_rename_last_updated_at_department_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=True, verbose_name='admin'),
        ),
    ]
