# Generated by Django 4.1.3 on 2023-02-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0008_rename_is_admin_user_admin_user_is_active_user_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='contact_details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
